---
title: "Gene level data"
output: html_notebook
---

```{r setup}
require(tidyverse)
require(fst)
require(furrr)
```



```{r paged.print=TRUE}

files <- list.files('../../data/Lung', full.names = T, pattern = 'txt$')
files <- set_names(files, str_replace(basename(files), '.txt',''))
files_fst <- map(files,str_c,'.fst')
Lung_GeneExpression <- read_fst(files_fst$Lung_GeneExpression) %>% as_data_frame
Lung_GeneExpression_transposed <- Lung_GeneExpression %>% 
  gather(SampleID, value = gene_expression, starts_with("TCGA")) %>% select(Gene,Chr,gene_expression,SampleID) %>%
  tidyr::unite(gene_chr, Gene,Chr) %>% 
  distinct(SampleID, gene_chr,.keep_all=TRUE)
Lung_CNV <- read_fst(files_fst$Lung_CNV) %>% as_data_frame
Lung_CNV_transposed <- Lung_CNV %>% 
  gather(SampleID, value = cnv, starts_with("TCGA")) %>% select(Gene,Chr,cnv,SampleID) %>%
  tidyr::unite(gene_chr, Gene,Chr) %>% 
  distinct(SampleID, gene_chr,.keep_all=TRUE)
Lung_Mutation <- read_fst(files_fst$Lung_Mutation) %>% as_data_frame
Lung_Mutation_transposed <- Lung_Mutation %>%
  gather(SampleID, value = Effect, starts_with("TCGA")) %>% select(Gene,Chr,Effect,SampleID=Sample_ID) %>%
  tidyr::unite(gene_chr, Gene,Chr) %>%
  distinct(SampleID, gene_chr,.keep_all=TRUE)
```


```{r}
joined_data <- list(Lung_GeneExpression_transposed,Lung_CNV_transposed,Lung_Mutation_transposed) %>% 
 reduce(inner_join, by = c("SampleID","gene_chr"))
```

```{r}
write_fst(joined_data, '../../data/intermediates/joined_gene_data.fst' )
```



