---
title: "Methylation"
output: html_notebook
---


```{r}
require(fst)
require(tidyr)
require(dplyr)
library(data.table)
library(dplyr)
library(stringr)

```

```{r}
Lung_CNV <- read_fst('../../data/startset/Lung_CNV.txt.fst') %>% as_data_frame
Lung_Methylation <- read_fst('../../data/startset/Lung_Methylation.txt.fst') %>% as_data_frame
Lung_Methylation = Lung_Methylation  %>% mutate(Gene = sub(',.*','', Gene))

# remove duplicates from CNV
ind.duplicate = duplicated(Lung_CNV %>% select(Gene, Chr))

# remove rows with NA (genes with no location)
Lung_CNV = Lung_CNV[!ind.duplicate,] %>% na.omit() %>% as_data_frame
```




```{r}

M = 10000

head(Lung_CNV)



# create data frame with interval for each gene_chr
gene_start_stop = 
  Lung_CNV %>% 
  select(Chr, Gene, Start, Stop) %>% 
  mutate(Gene_Start = Start, Gene_Stop = Stop) %>% 
  select(-c(Start,Stop)) %>% 
  mutate(Gene_Start_Int = Gene_Start - M, Gene_Stop_Int = Gene_Stop + M) %>% 
  as_data_frame

head(gene_start_stop)

# get probe_location
probe_location = 
  Lung_Methylation %>% select(probeID, Chr, Gene, Start) %>% 
  mutate(Gene = sub(',.*','', Gene)) %>% 
  as_data_frame

head(probe_location)


# remove NAs
probe_location = probe_location %>% na.omit() %>% as_data_frame()
sum(is.na(probe_location$Start))

# join CNV gene location, and probe location
join = inner_join(gene_start_stop, probe_location, by = c("Chr", "Gene")) %>% as_data_frame 

head(join)

# Find probes within gene interval
join_true =  join[(join$Start > join$Gene_Start_Int & join$Start < join$Gene_Stop_Int),] %>% as_data_frame()

# Select probes within gene interval


Lung_Methylation_Sig = Lung_Methylation %>% filter(probeID %in% join_true$probeID) %>% as_data_frame()
Lung_Methylation_Sig = Lung_Methylation_Sig %>% select(-c(Start, Strand, Stop, Relation_CpG_Island, probeID))

head(Lung_Methylation_Sig)

ind.na = (rowSums(is.na(Lung_Methylation_Sig %>% select(-c(Chr, Gene)))) == 907)
Lung_Methylation_Sig = Lung_Methylation_Sig[!ind.na,]



head(Lung_Methylation_Sig)



# get Average methylation level in each gene_chr
Lung_Methylation_Avg = Lung_Methylation_Sig %>% group_by(Chr, Gene) %>% summarize_at(.vars = vars(starts_with('TCGA')), .funs = mean, na.rm=TRUE) %>% as.data.frame


Lung_Methylation_Avg = Lung_Methylation_Avg %>% mutate(Gene_Chr = str_c(Gene,"_",Chr)) %>% select(-c(Chr, Gene))
Lung_Methylation_Avg = Lung_Methylation_Avg %>% as_data_frame()
head(Lung_Methylation_Avg)

#check
sum(is.na(Lung_Methylation_Avg))

# 
Lung_Methylation_Avg_t <- Lung_Methylation_Avg %>% 
  gather(SampleID,methyl, starts_with('TCGA')) %>% 
  spread(Gene_Chr,methyl)

head(Lung_Methylation_Avg_t)

write_fst(Lung_Methylation_Avg_t, "C:/Users/Robert/Documents/data/intermediates/Lung_Methylation_Transposed.fst")


``` 